// This file is auto-generated by Supabase CLI.
// Run: supabase gen types typescript --local > types/supabase.ts
// Manually maintained until Supabase CLI is available.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    PostgrestVersion: '12';
    Tables: {
      organizations: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          name: string;
          slug: string;
          logo_url: string | null;
          banner_url: string | null;
          colors: Json | null;
          plan: 'starter' | 'pro' | 'business';
          subscription_status: 'active' | 'trialing' | 'past_due' | 'cancelled';
          stripe_customer_id: string | null;
          trial_ends_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name: string;
          slug: string;
          logo_url?: string | null;
          banner_url?: string | null;
          colors?: Json | null;
          plan?: 'starter' | 'pro' | 'business';
          subscription_status?: 'active' | 'trialing' | 'past_due' | 'cancelled';
          stripe_customer_id?: string | null;
          trial_ends_at?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>;
        Relationships: [];
      };
      branches: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          name: string;
          address: string | null;
          timezone: string;
          is_active: boolean;
          is_temporarily_closed: boolean;
          closed_message: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          name: string;
          address?: string | null;
          timezone?: string;
          is_active?: boolean;
          is_temporarily_closed?: boolean;
          closed_message?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['branches']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'branches_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          }
        ];
      };
      staff_users: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          auth_user_id: string | null;
          branch_id: string | null;
          name: string;
          email: string | null;
          role: 'super_admin' | 'manager' | 'waiter' | 'kitchen';
          pin_hash: string | null;
          is_active: boolean;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          auth_user_id?: string | null;
          branch_id?: string | null;
          name: string;
          email?: string | null;
          role: 'super_admin' | 'manager' | 'waiter' | 'kitchen';
          pin_hash?: string | null;
          is_active?: boolean;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['staff_users']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'staff_users_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          }
        ];
      };
      menu_categories: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          name: string;
          icon: string | null;
          color: string | null;
          sort_order: number;
          is_visible: boolean;
          schedule_start: string | null;
          schedule_end: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          name: string;
          icon?: string | null;
          color?: string | null;
          sort_order?: number;
          is_visible?: boolean;
          schedule_start?: string | null;
          schedule_end?: string | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['menu_categories']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'menu_categories_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          }
        ];
      };
      menu_items: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          category_id: string;
          name: string;
          description: string | null;
          price: number;
          is_available: boolean;
          is_sold_out_today: boolean;
          sort_order: number;
          prep_time: number | null;
          is_special: boolean;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          category_id: string;
          name: string;
          description?: string | null;
          price: number;
          is_available?: boolean;
          is_sold_out_today?: boolean;
          sort_order?: number;
          prep_time?: number | null;
          is_special?: boolean;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['menu_items']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'menu_items_category_id_fkey';
            columns: ['category_id'];
            isOneToOne: false;
            referencedRelation: 'menu_categories';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'menu_items_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          }
        ];
      };
      menu_item_photos: {
        Row: {
          id: string;
          created_at: string;
          menu_item_id: string;
          url: string;
          position: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          menu_item_id: string;
          url: string;
          position?: number;
        };
        Update: Partial<Database['public']['Tables']['menu_item_photos']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'menu_item_photos_menu_item_id_fkey';
            columns: ['menu_item_id'];
            isOneToOne: false;
            referencedRelation: 'menu_items';
            referencedColumns: ['id'];
          }
        ];
      };
      menu_item_filters: {
        Row: {
          id: string;
          menu_item_id: string;
          filter: 'vegetariano' | 'sin_gluten' | 'picante' | 'vegano';
        };
        Insert: {
          id?: string;
          menu_item_id: string;
          filter: 'vegetariano' | 'sin_gluten' | 'picante' | 'vegano';
        };
        Update: Partial<Database['public']['Tables']['menu_item_filters']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'menu_item_filters_menu_item_id_fkey';
            columns: ['menu_item_id'];
            isOneToOne: false;
            referencedRelation: 'menu_items';
            referencedColumns: ['id'];
          }
        ];
      };
      menu_item_branch_overrides: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          menu_item_id: string;
          branch_id: string;
          price_override: number | null;
          is_available: boolean | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          menu_item_id: string;
          branch_id: string;
          price_override?: number | null;
          is_available?: boolean | null;
        };
        Update: Partial<Database['public']['Tables']['menu_item_branch_overrides']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'menu_item_branch_overrides_menu_item_id_fkey';
            columns: ['menu_item_id'];
            isOneToOne: false;
            referencedRelation: 'menu_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'menu_item_branch_overrides_branch_id_fkey';
            columns: ['branch_id'];
            isOneToOne: false;
            referencedRelation: 'branches';
            referencedColumns: ['id'];
          }
        ];
      };
      price_change_history: {
        Row: {
          id: string;
          created_at: string;
          menu_item_id: string;
          old_price: number;
          new_price: number;
          changed_by: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          menu_item_id: string;
          old_price: number;
          new_price: number;
          changed_by?: string | null;
        };
        Update: Partial<Database['public']['Tables']['price_change_history']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'price_change_history_menu_item_id_fkey';
            columns: ['menu_item_id'];
            isOneToOne: false;
            referencedRelation: 'menu_items';
            referencedColumns: ['id'];
          }
        ];
      };
      design_templates: {
        Row: {
          id: string;
          name: string;
          slug: string;
          preview_url: string | null;
          config: Json;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          preview_url?: string | null;
          config?: Json;
        };
        Update: Partial<Database['public']['Tables']['design_templates']['Insert']>;
        Relationships: [];
      };
      org_settings: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          key: string;
          value: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          key: string;
          value?: string | null;
        };
        Update: Partial<Database['public']['Tables']['org_settings']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'org_settings_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          }
        ];
      };
      org_texts: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          key: string;
          value: string;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          key: string;
          value: string;
        };
        Update: Partial<Database['public']['Tables']['org_texts']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'org_texts_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          }
        ];
      };
      audit_log: {
        Row: {
          id: string;
          created_at: string;
          organization_id: string | null;
          user_id: string | null;
          action: string;
          resource: string;
          resource_id: string | null;
          old_value: Json | null;
          new_value: Json | null;
          ip_address: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          organization_id?: string | null;
          user_id?: string | null;
          action: string;
          resource: string;
          resource_id?: string | null;
          old_value?: Json | null;
          new_value?: Json | null;
          ip_address?: string | null;
        };
        Update: Partial<Database['public']['Tables']['audit_log']['Insert']>;
        Relationships: [];
      };
      customers: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          name: string;
          phone_encrypted: string;
          phone_last4: string;
          segment: 'new' | 'frequent' | 'dormant';
          visit_count: number;
          last_visit_at: string | null;
          birthday: string | null;
          notes: string | null;
          is_opted_in: boolean;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          name: string;
          phone_encrypted: string;
          phone_last4: string;
          segment?: 'new' | 'frequent' | 'dormant';
          visit_count?: number;
          last_visit_at?: string | null;
          birthday?: string | null;
          notes?: string | null;
          is_opted_in?: boolean;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['customers']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'customers_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          }
        ];
      };
      customer_visits: {
        Row: {
          id: string;
          customer_id: string;
          organization_id: string;
          branch_id: string | null;
          visited_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          organization_id: string;
          branch_id?: string | null;
          visited_at?: string;
        };
        Update: Partial<Database['public']['Tables']['customer_visits']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'customer_visits_customer_id_fkey';
            columns: ['customer_id'];
            isOneToOne: false;
            referencedRelation: 'customers';
            referencedColumns: ['id'];
          }
        ];
      };
      customer_consents: {
        Row: {
          id: string;
          created_at: string;
          customer_id: string;
          consent_type: 'marketing' | 'data_processing';
          granted: boolean;
          ip_address: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          customer_id: string;
          consent_type: 'marketing' | 'data_processing';
          granted: boolean;
          ip_address?: string | null;
        };
        Update: Partial<Database['public']['Tables']['customer_consents']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'customer_consents_customer_id_fkey';
            columns: ['customer_id'];
            isOneToOne: false;
            referencedRelation: 'customers';
            referencedColumns: ['id'];
          }
        ];
      };
      restaurant_tables: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          number: number;
          label: string | null;
          zone: string | null;
          capacity: number | null;
          is_active: boolean;
          qr_token: string | null;
          deleted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          number: number;
          label?: string | null;
          zone?: string | null;
          capacity?: number | null;
          is_active?: boolean;
          qr_token?: string | null;
          deleted_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['restaurant_tables']['Insert']>;
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          table_id: string | null;
          table_number: number | null;
          status: 'pending' | 'confirmed' | 'preparing' | 'ready' | 'delivered' | 'cancelled';
          notes: string | null;
          total: number;
          customer_name: string | null;
          round: number;
          confirmed_by: string | null;
          confirmed_at: string | null;
          ready_at: string | null;
          delivered_at: string | null;
          cancelled_at: string | null;
          cancel_reason: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          table_id?: string | null;
          table_number?: number | null;
          status?: 'pending' | 'confirmed' | 'preparing' | 'ready' | 'delivered' | 'cancelled';
          notes?: string | null;
          total?: number;
          customer_name?: string | null;
          round?: number;
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          ready_at?: string | null;
          delivered_at?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
        Relationships: [];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          menu_item_id: string;
          name: string;
          price: number;
          quantity: number;
          notes: string | null;
          is_ready: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          menu_item_id: string;
          name: string;
          price: number;
          quantity?: number;
          notes?: string | null;
          is_ready?: boolean;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['order_items']['Insert']>;
        Relationships: [];
      };
      order_status_history: {
        Row: {
          id: string;
          order_id: string;
          status: string;
          changed_by: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          status: string;
          changed_by?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['order_status_history']['Insert']>;
        Relationships: [];
      };
      loyalty_programs: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          stamps_required: number;
          reward_type: 'free_item' | 'discount' | 'custom';
          reward_value: string;
          expiration_days: number | null;
          is_active: boolean;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          stamps_required?: number;
          reward_type: 'free_item' | 'discount' | 'custom';
          reward_value: string;
          expiration_days?: number | null;
          is_active?: boolean;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['loyalty_programs']['Insert']>;
        Relationships: [];
      };
      stamp_cards: {
        Row: {
          id: string;
          program_id: string;
          customer_id: string;
          organization_id: string;
          stamp_count: number;
          is_complete: boolean;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          customer_id: string;
          organization_id: string;
          stamp_count?: number;
          is_complete?: boolean;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['stamp_cards']['Insert']>;
        Relationships: [];
      };
      stamps: {
        Row: {
          id: string;
          stamp_card_id: string;
          customer_id: string;
          branch_id: string | null;
          granted_by: string | null;
          stamped_at: string;
        };
        Insert: {
          id?: string;
          stamp_card_id: string;
          customer_id: string;
          branch_id?: string | null;
          granted_by?: string | null;
          stamped_at?: string;
        };
        Update: Partial<Database['public']['Tables']['stamps']['Insert']>;
        Relationships: [];
      };
      rewards: {
        Row: {
          id: string;
          stamp_card_id: string;
          customer_id: string;
          organization_id: string;
          code: string;
          redeemed_at: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          stamp_card_id: string;
          customer_id: string;
          organization_id: string;
          code: string;
          redeemed_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['rewards']['Insert']>;
        Relationships: [];
      };
      branch_schedules: {
        Row: {
          id: string;
          branch_id: string;
          organization_id: string;
          day_of_week: number;
          opens_at: string;
          closes_at: string;
          is_open: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          branch_id: string;
          organization_id: string;
          day_of_week: number;
          opens_at: string;
          closes_at: string;
          is_open?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['branch_schedules']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'branch_schedules_branch_id_fkey';
            columns: ['branch_id'];
            isOneToOne: false;
            referencedRelation: 'branches';
            referencedColumns: ['id'];
          }
        ];
      };
      campaigns: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          name: string;
          template_id: string | null;
          template_variables: Json | null;
          segment: 'all' | 'new' | 'frequent' | 'dormant' | null;
          status: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
          scheduled_at: string | null;
          sent_at: string | null;
          total_sent: number;
          total_delivered: number;
          total_read: number;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          name: string;
          template_id?: string | null;
          template_variables?: Json | null;
          segment?: 'all' | 'new' | 'frequent' | 'dormant' | null;
          status?: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
          scheduled_at?: string | null;
          sent_at?: string | null;
          total_sent?: number;
          total_delivered?: number;
          total_read?: number;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['campaigns']['Insert']>;
        Relationships: [
          {
            foreignKeyName: 'campaigns_organization_id_fkey';
            columns: ['organization_id'];
            isOneToOne: false;
            referencedRelation: 'organizations';
            referencedColumns: ['id'];
          }
        ];
      };
    };
    Views: Record<string, {
      Row: Record<string, unknown>;
      Relationships: never[];
    }>;
    Functions: {
      get_user_org_id: {
        Args: Record<string, never>;
        Returns: string;
      };
      get_user_role: {
        Args: Record<string, never>;
        Returns: string;
      };
      encrypt_phone: {
        Args: { phone: string; key: string };
        Returns: string;
      };
      decrypt_phone: {
        Args: { encrypted: string; key: string };
        Returns: string;
      };
    };
    Enums: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
