// This file is auto-generated by Supabase CLI.
// Run: supabase gen types typescript --local > types/supabase.ts
// Placeholder until Supabase project is initialized.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          name: string;
          slug: string;
          logo_url: string | null;
          colors: Json | null;
          plan: 'starter' | 'pro' | 'business';
          subscription_status: 'active' | 'trialing' | 'past_due' | 'cancelled';
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          name: string;
          slug: string;
          logo_url?: string | null;
          colors?: Json | null;
          plan?: 'starter' | 'pro' | 'business';
          subscription_status?: 'active' | 'trialing' | 'past_due' | 'cancelled';
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>;
      };
      branches: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          name: string;
          address: string | null;
          timezone: string;
          is_active: boolean;
          is_temporarily_closed: boolean;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          name: string;
          address?: string | null;
          timezone?: string;
          is_active?: boolean;
          is_temporarily_closed?: boolean;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['branches']['Insert']>;
      };
      menu_categories: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          organization_id: string;
          name: string;
          icon: string | null;
          color: string | null;
          sort_order: number;
          is_visible: boolean;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          organization_id: string;
          name: string;
          icon?: string | null;
          color?: string | null;
          sort_order?: number;
          is_visible?: boolean;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['menu_categories']['Insert']>;
      };
      menu_items: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          category_id: string;
          organization_id: string;
          name: string;
          description: string | null;
          price: number;
          is_available: boolean;
          is_sold_out_today: boolean;
          sort_order: number;
          prep_time: number | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          category_id: string;
          organization_id: string;
          name: string;
          description?: string | null;
          price: number;
          is_available?: boolean;
          is_sold_out_today?: boolean;
          sort_order?: number;
          prep_time?: number | null;
          deleted_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['menu_items']['Insert']>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
